server:
  port: 8083
spring:
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    #HTML5严格模式
    mode: HTML5
    cache: false
  http:
    multipart:
      maxFileSize: 100Mb
      maxRequestSize: 1000Mb
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xiafei.newsbackend.pojo
  configuration:
    map-underscore-to-camel-case: true
    use-column-label: true
    use-generated-keys: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count,countSql